use_half: False
use_ddp: False

work_dir: ./result
data_path: data/fz1
data_meta: data/fz1/fz1_train.json
content_font: "FZSong"


batch_size: 1
n_workers: 0
comb_iter: 800000
fact_iter: 50000
g_lr: 2e-4
d_lr: 8e-4
ac_lr: 2e-4
adam_betas: [0.0, 0.9]

cv_n_unis: 30
cv_n_fonts: 10

print_freq: 1
val_freq: 2
save_freq: 5
tb_freq: 10